version: '3.4'

services:

  chatgpt_postgres:
    container_name: chatgpt_postgres
    image: postgres:11.5
    volumes:
      - ./.docker/postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_bot_local_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"


volumes:
  chatgpt_postgres:
    driver: local
